# Generated by Django 5.1.4 on 2025-01-02 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsal',
            options={'ordering': ['date', 'time'], 'verbose_name': 'Rehearsal', 'verbose_name_plural': 'Rehearsals'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['title'], 'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='participants',
            field=models.ManyToManyField(related_name='rehearsals', to=settings.AUTH_USER_MODEL, verbose_name='Participants'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='songs',
            field=models.ManyToManyField(related_name='rehearsals', to='rehearsals.song', verbose_name='Songs'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=100, verbose_name='Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='chords',
            field=models.TextField(blank=True, null=True, verbose_name='Chords'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, null=True, verbose_name='Lyrics'),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
