# Generated by Django 5.1.4 on 2025-01-02 13:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0002_alter_rehearsal_options_alter_song_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={},
        ),
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='chords',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_and_chords',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Lyrics and Chords'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
