# Generated by Django 5.1.4 on 2025-01-02 14:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0003_alter_song_options_remove_song_artist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rehearsal',
            options={},
        ),
        migrations.RemoveField(
            model_name='rehearsal',
            name='date',
        ),
        migrations.RemoveField(
            model_name='rehearsal',
            name='time',
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='date_option_1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date and Time Option 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='date_option_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time Option 2'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='date_option_3',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date and Time Option 3'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='selected_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Selected Date and Time'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics_and_chords',
            field=models.TextField(default='', verbose_name='Lyrics and Chords'),
        ),
    ]
