# Generated by Django 5.1.4 on 2025-02-18 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0004_alter_rehearsal_options_remove_rehearsal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rehearsal',
            name='selected_date',
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='time_option_1',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario primera opción'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='time_option_2',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario segunda opción'),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='time_option_3',
            field=models.TimeField(blank=True, null=True, verbose_name='Horario tercera opción'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='date_option_1',
            field=models.DateField(verbose_name='Primera opción de fecha'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='date_option_2',
            field=models.DateField(blank=True, null=True, verbose_name='Segunda opción de fecha'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='date_option_3',
            field=models.DateField(blank=True, null=True, verbose_name='Tercera opción de fecha'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='rehearsal',
            name='songs',
            field=models.ManyToManyField(to='rehearsals.song', verbose_name='Canciones'),
        ),
    ]
