# Generated by Django 5.1.4 on 2025-02-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehearsals', '0005_remove_rehearsal_selected_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsal',
            name='final_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha definitiva'),
        ),
    ]
